#define MQTT_SERVER "awesome-fisher.cloudmqtt.com"
#define MQTT_PORT 1883
#define MQTT_USERNAME "gkvpckep"
#define MQTT_PASSWORD "yGbZQKc8MAma"
#define BUFFER_SIZE_SECTIONS 5
#define BUFFER_SIZE_BEATS 30
#define BUFFER_SIZE_SEGMENTS 70
#define SAMPLE_DEGREE 2
#define SAMPLE_RATE 0.01